name: flash_list
description: A high-performance Flutter ListView widget with pagination, pull-to-refresh, and header features inspired by React Native's FlashList.
version: 0.0.1
homepage: https://github.com/yourusername/flash_list

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
